// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0joOuB3OuKy4cEBRIwS3Cpsk4VC5reI',
    appId: '1:511088898989:web:ebc9103467ed39355f2724',
    messagingSenderId: '511088898989',
    projectId: 'flutter-fire-event',
    authDomain: 'flutter-fire-event.firebaseapp.com',
    storageBucket: 'flutter-fire-event.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByk5rGEACjjDMZauf7KEKF-M5iEdmVcM',
    appId: '1:511088898989:android:d70b62cb70b5b12d5f2724',
    messagingSenderId: '511088898989',
    projectId: 'flutter-fire-event',
    storageBucket: 'flutter-fire-event.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvPomdEC0mcPAqYT4WhChMJc6C-JCN7Q',
    appId: '1:511088898989:ios:de1903600430189c5f2724',
    messagingSenderId: '511088898989',
    projectId: 'flutter-fire-event',
    storageBucket: 'flutter-fire-event.firebasestorage.app',
    iosBundleId: 'com.example.flutterCalendarZadach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvPomdEC0mcPAqYT4WhChMJc6C-JCN7Q',
    appId: '1:511088898989:ios:de1903600430189c5f2724',
    messagingSenderId: '511088898989',
    projectId: 'flutter-fire-event',
    storageBucket: 'flutter-fire-event.firebasestorage.app',
    iosBundleId: 'com.example.flutterCalendarZadach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd0joOuB3OuKy4cEBRIwS3Cpsk4VC5reI',
    appId: '1:511088898989:web:be99dbef6ad1253b5f2724',
    messagingSenderId: '511088898989',
    projectId: 'flutter-fire-event',
    authDomain: 'flutter-fire-event.firebaseapp.com',
    storageBucket: 'flutter-fire-event.firebasestorage.app',
  );
}
